<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><ProjectReference Include="../Aetheric.Provisioning.Application/Aetheric.Provisioning.Application.csproj" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.11.2" />
  </ItemGroup>
</Project>
